name: Run Frontend Tests
description: "composite run action"
runs:
  using: "composite"
  steps:
    - run: cd ./frontend && npm run eslint
      shell: bash
    - run: cd ./frontend && npm run test:ci
      shell: bash
    - run: cd ./frontend && npm run build
      shell: bash
